# Generated by Django 3.0.7 on 2020-09-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('Organization_name', models.CharField(max_length=100)),
                ('Organization_type', models.CharField(max_length=100)),
                ('mfl_code', models.CharField(default='', max_length=100)),
                ('postal_address', models.CharField(default='', max_length=100)),
                ('physical_address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('currency', models.CharField(default='Ksh.', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100)),
                ('company_phone', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('department', models.IntegerField(choices=[(0, 'Records'), (1, 'Revenue'), (2, 'Outpatient'), (3, 'Laboratory'), (4, 'Radiology'), (5, 'Pharmacy'), (6, 'Inpatient'), (7, 'General')])),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rebate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('bed_capacity', models.IntegerField(default=0)),
                ('admissions', models.IntegerField(default=0)),
                ('admission_fee', models.IntegerField(default=0)),
                ('daily_fee', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
