# Generated by Django 3.0.7 on 2020-09-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='clinic',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_clinic_related', related_query_name='organization_clinics', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_insurance_related', related_query_name='organization_insurances', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_service_related', related_query_name='organization_services', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='ward',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_ward_related', related_query_name='organization_wards', to='common.Organization'),
        ),
    ]
