# Generated by Django 3.0.7 on 2020-09-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('organization', '0002_auto_20200918_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_clinic', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_insurance', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_service', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_ward', to='common.Organization'),
        ),
    ]
