# Generated by Django 3.0.7 on 2020-09-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200918_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='desc',
        ),
        migrations.AddField(
            model_name='clinic',
            name='appointment_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinic',
            name='appointments',
            field=models.IntegerField(default=0),
        ),
    ]
