# Generated by Django 3.0.7 on 2020-09-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('inpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_admission_related', related_query_name='inpatient_admissions', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_intervention_related', related_query_name='inpatient_interventions', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='review',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_review_related', related_query_name='inpatient_reviews', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='vitalmonitor',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_vitalmonitor_related', related_query_name='inpatient_vitalmonitors', to='common.Organization'),
        ),
    ]
