# Generated by Django 3.0.7 on 2020-09-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('inpatient', '0002_auto_20200918_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_admission', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_intervention', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='review',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_review', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='vitalmonitor',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inpatient_vitalmonitor', to='common.Organization'),
        ),
    ]
