# Generated by Django 3.0.7 on 2020-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_auto_20200918_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='org',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='org',
        ),
        migrations.RemoveField(
            model_name='review',
            name='org',
        ),
        migrations.RemoveField(
            model_name='vitalmonitor',
            name='org',
        ),
    ]
