# Generated by Django 3.0.7 on 2020-09-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('patient_id', models.IntegerField(default=0)),
                ('service_request_id', models.IntegerField(default=0)),
                ('investigation', models.CharField(blank=True, max_length=255, null=True)),
                ('specimen', models.CharField(blank=True, max_length=100, null=True)),
                ('sampling_comment', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
                ('analysed_at', models.DateTimeField(null=True)),
                ('analysed_by', models.IntegerField(default=0)),
                ('analysis_comment', models.TextField(null=True)),
                ('verified_at', models.DateTimeField(null=True)),
                ('verified_by', models.IntegerField(default=0)),
                ('verification_comment', models.TextField(null=True)),
                ('is_analysed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
