# Generated by Django 3.0.7 on 2020-09-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name', models.CharField(max_length=100)),
                ('Organization_type', models.CharField(max_length=100)),
                ('mfl_code', models.CharField(default='', max_length=100)),
                ('postal_address', models.CharField(default='', max_length=100)),
                ('physical_address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('currency', models.CharField(default='Ksh.', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
