# Generated by Django 3.0.7 on 2020-09-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='Organization_name',
            new_name='hospital_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='Organization_type',
            new_name='hospital_type',
        ),
    ]
