# Generated by Django 3.0.7 on 2020-09-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200918_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='hospital_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='hospital_type',
            new_name='organization_type',
        ),
    ]
