# Generated by Django 3.0.7 on 2020-09-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('drug_id', models.IntegerField(default=0)),
                ('quantity_before', models.IntegerField(default=0)),
                ('dispensed_quantity', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('act_ing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('exc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('act_ing_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(blank=True, max_length=100, null=True)),
                ('smell', models.CharField(blank=True, max_length=100, null=True)),
                ('taste', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('drug_id', models.IntegerField(default=0)),
                ('drug_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_before', models.IntegerField(default=0)),
                ('new_stock_quantity', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField(default=0)),
                ('batch_number', models.CharField(max_length=200, unique=True)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
