# Generated by Django 3.0.7 on 2020-09-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_dispense_related', related_query_name='pharmacy_dispenses', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='drug',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_drug_related', related_query_name='pharmacy_drugs', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='reorder',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_reorder_related', related_query_name='pharmacy_reorders', to='common.Organization'),
        ),
    ]
