# Generated by Django 3.0.7 on 2020-09-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200925_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='can_dispense',
            new_name='can_dispense_drug',
        ),
        migrations.RemoveField(
            model_name='group',
            name='can_edit_queue',
        ),
    ]
