# Generated by Django 3.0.7 on 2020-09-21 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0008_auto_20200920_1437'),
        ('common', '0003_auto_20200918_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('BILLED', 'billed'), ('PAID', 'paid')], default='DRAFT', max_length=200)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_invoice', to='common.Organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_invoice_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient_id', 'status')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_id', models.IntegerField(default=0)),
                ('admission_id', models.IntegerField(default=0)),
                ('service_id', models.IntegerField(default=0)),
                ('service_name', models.CharField(max_length=200)),
                ('department', models.IntegerField(choices=[(0, 'Records'), (1, 'Revenue'), (2, 'Outpatient'), (3, 'Laboratory'), (4, 'Radiology'), (5, 'Pharmacy'), (6, 'Inpatient'), (7, 'General')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_served', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_servicerequest_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='revenue.Invoice')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_servicerequest', to='common.Organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient')),
                ('payment_received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_servicerequest_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_deposit_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_deposit', to='common.Organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_deposit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
