# Generated by Django 3.0.7 on 2020-09-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200920_1437'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('patient_id', 'status')},
        ),
    ]
