# Generated by Django 3.0.7 on 2020-09-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0005_auto_20200921_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
