# Generated by Django 3.0.7 on 2020-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0007_auto_20200924_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('BILLED', 'billed'), ('CLEARED', 'cleared')], default='DRAFT', max_length=200),
        ),
    ]
