# Generated by Django 3.0.7 on 2020-09-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_category_related', related_query_name='inventory_categorys', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_order_related', related_query_name='inventory_orders', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product_related', related_query_name='inventory_products', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requisition_related', related_query_name='inventory_requisitions', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='store',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_store_related', related_query_name='inventory_stores', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_supplier_related', related_query_name='inventory_suppliers', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_unit_related', related_query_name='inventory_units', to='common.Organization'),
        ),
    ]
