# Generated by Django 3.0.7 on 2020-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200918_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='org',
        ),
        migrations.RemoveField(
            model_name='order',
            name='org',
        ),
        migrations.RemoveField(
            model_name='product',
            name='org',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='org',
        ),
        migrations.RemoveField(
            model_name='store',
            name='org',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='org',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='org',
        ),
    ]
