# Generated by Django 3.0.7 on 2020-09-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('patient_id', models.IntegerField(default=0)),
                ('clinic_id', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session_with', models.IntegerField(default=0)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('discharge_note', models.TextField(null=True)),
                ('is_discharged', models.BooleanField(default=False)),
                ('discharged_by', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('appointment_id', models.IntegerField(default=0)),
                ('disease', models.CharField(max_length=250)),
                ('icd_10', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('appointment_id', models.IntegerField(default=0)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=10, null=True)),
                ('period_units', models.CharField(blank=True, max_length=10, null=True)),
                ('pre_med_note', models.TextField(blank=True, null=True)),
                ('physical_examination_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('appointment_id', models.IntegerField(default=0)),
                ('bp_systolic', models.CharField(blank=True, max_length=10, null=True)),
                ('bp_diastolic', models.CharField(blank=True, max_length=10, null=True)),
                ('pulse', models.CharField(blank=True, max_length=10, null=True)),
                ('mass', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('triage_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
