# Generated by Django 3.0.7 on 2020-09-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('outpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_appointment_related', related_query_name='outpatient_appointments', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_diagnosis_related', related_query_name='outpatient_diagnosiss', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='observation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_observation_related', related_query_name='outpatient_observations', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='vital',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_vital_related', related_query_name='outpatient_vitals', to='common.Organization'),
        ),
    ]
