# Generated by Django 3.0.7 on 2020-09-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('outpatient', '0002_auto_20200918_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_appointment', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_diagnosis', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_observation', to='common.Organization'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_vital', to='common.Organization'),
        ),
    ]
