# Generated by Django 3.0.7 on 2020-09-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0004_auto_20200918_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='org',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='org',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='org',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='org',
        ),
    ]
