# Generated by Django 3.0.7 on 2020-09-21 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpatient', '0005_auto_20200918_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
