# Generated by Django 3.0.7 on 2020-09-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0006_auto_20200921_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='session_with',
        ),
    ]
