# Generated by Django 3.0.7 on 2020-09-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0007_remove_appointment_session_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_checked_in',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_discharged',
        ),
    ]
