# Generated by Django 3.0.7 on 2020-09-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0008_auto_20200927_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
