# Generated by Django 3.0.7 on 2020-10-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0009_appointment_is_discharged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
