# Generated by Django 3.0.7 on 2020-10-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_auto_20200918_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologylogbook',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='radiologylogbook',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
