# Generated by Django 3.0.7 on 2020-09-18 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('fullname', models.CharField(max_length=100)),
                ('id_type', models.IntegerField(choices=[(0, 'Birth Certificate'), (1, 'National ID'), (2, 'Alien ID'), (3, 'Military ID'), (4, 'Passport')], default=1)),
                ('id_no', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Inter-sex')], default=0)),
                ('marital_status', models.IntegerField(choices=[(0, 'Child'), (1, 'Single '), (2, 'Married '), (3, 'Separated '), (4, ' Divorced ')], default=0)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('postal_address', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('ward_estate', models.CharField(blank=True, max_length=100)),
                ('kin_name', models.CharField(max_length=100)),
                ('kin_phone', models.CharField(max_length=100)),
                ('kin_relationship', models.IntegerField(choices=[(0, 'Father'), (1, 'Mother'), (2, 'Brother'), (3, 'Sister'), (4, 'Husband'), (5, 'Wife'), (6, 'Guardian')], default=0)),
                ('kin_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('id_type', 'id_no')},
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('card_number', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Insurance')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_insurances', to='records.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
