# Generated by Django 3.0.7 on 2020-09-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_patient_related', related_query_name='records_patients', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_patientinsurance_related', related_query_name='records_patientinsurances', to='common.Organization'),
        ),
    ]
