# Generated by Django 3.0.7 on 2020-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200918_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
