# Generated by Django 3.0.7 on 2020-09-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_patient_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinsurance',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient'),
        ),
    ]
