# Generated by Django 3.0.7 on 2020-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200920_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='org',
        ),
        migrations.RemoveField(
            model_name='patientinsurance',
            name='org',
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
    ]
