# Generated by Django 3.0.7 on 2020-09-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200920_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
    ]
