# Generated by Django 3.0.7 on 2020-10-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_patient_is_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
