# Generated by Django 3.0.7 on 2020-09-18 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('reply', models.TextField()),
                ('bug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_replies', to='bugs.Bug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
