# Generated by Django 3.0.7 on 2020-09-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20200918_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='bug_id',
        ),
        migrations.AddField(
            model_name='replies',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs_replies', to='bugs.Bug'),
        ),
    ]
