# Generated by Django 3.0.7 on 2020-09-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20200918_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bugs.Bug'),
        ),
    ]
