name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  AlLOWED_ORIGINS: ${{ secrets.AlLOWED_ORIGINS }}

  DEBUG: ${{ secrets.DEBUG }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

  # email
  EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

  # mobile money
  MPESA_BUSINESS_SHORT_CODE: ${{ secrets.MPESA_BUSINESS_SHORT_CODE }}
  MPESA_CONSUMER_KEY: ${{ secrets.MPESA_CONSUMER_KEY }}
  MPESA_CONSUMER_SECRETE: ${{ secrets.MPESA_CONSUMER_SECRETE }}
  MPESA_ONLINE_PASSKEY: ${{ secrets.MPESA_ONLINE_PASSKEY }}
  MPESA_CALLBACK_URL: ${{ secrets.MPESA_CALLBACK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5433:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11"
      - name: Run migrations
        run: python manage.py migrate
      - name: Run Tests
        run: |
          python manage.py test
